/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modeloBeans.ClienteBean;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author luizk
 */
public class CadCliente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoCliente control = new DaoCliente();
    ClienteBean mod = new ClienteBean();
    int flag = 0;

    /**
     * Creates new form CadCliente
     */
    public CadCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new br.com.cyber.componente.KTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPesq = new br.com.cyber.componente.KTextField();
        txtEnd = new br.com.cyber.componente.KTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTel = new br.com.cyber.componente.KTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kComboBoxCid = new br.com.cyber.componente.KComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableCliente = new br.com.cyber.componente.Ktable();
        txtCpf = new br.com.cyber.componente.KTextField();
        txtNome = new br.com.cyber.componente.KTextField();
        jLabel7 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar);
        jButtonVoltar.setBounds(846, 413, 152, 34);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 300, 70, 40);

        txtCod.setEnabled(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        jPanel2.add(txtCod);
        txtCod.setBounds(120, 300, 50, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cpf:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 50, 70, 40);
        jPanel2.add(txtPesq);
        txtPesq.setBounds(550, 50, 230, 40);

        txtEnd.setEnabled(false);
        jPanel2.add(txtEnd);
        txtEnd.setBounds(120, 100, 230, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Endereço:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 100, 40);

        txtTel.setEnabled(false);
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        jPanel2.add(txtTel);
        txtTel.setBounds(120, 150, 230, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Telefone:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 100, 40);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);
        btnBuscar.setBounds(790, 50, 140, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nome:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 200, 70, 40);

        kComboBoxCid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        kComboBoxCid.setEnabled(false);
        jPanel2.add(kComboBoxCid);
        kComboBoxCid.setBounds(120, 250, 230, 40);

        ktableCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ktableCliente);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(550, 100, 452, 230);

        txtCpf.setEnabled(false);
        jPanel2.add(txtCpf);
        txtCpf.setBounds(120, 50, 230, 40);

        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(120, 200, 230, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cidade:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 250, 70, 40);

        btnNovo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo);
        btnNovo.setBounds(20, 370, 150, 40);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_save_1608823 (1).png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(180, 370, 150, 40);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_cancel-2_309095.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(340, 370, 160, 40);

        btnApagar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Streamline-70_185090.png"))); // NOI18N
        btnApagar.setText("APAGAR");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnApagar);
        btnApagar.setBounds(670, 370, 150, 40);

        btnEditar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_edit_2561427.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);
        btnEditar.setBounds(510, 370, 150, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 50, 1010, 460);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 1010, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -10, 1070, 540);

        setSize(new java.awt.Dimension(1048, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here

        flag = 1;
        txtCpf.setEnabled(true);
        txtEnd.setEnabled(true);
        kComboBoxCid.setEnabled(true);
        txtNome.setEnabled(true);
        txtTel.setEnabled(true);

        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtCod.setText("");
        txtCpf.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        txtPesq.setText("");
        txtTel.setText("");

        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        btnBuscar.setEnabled(false);
        txtPesq.setEnabled(false);
        ktableCliente.setEnabled(false);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (txtCpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtCpf.requestFocus();
        } else if (txtEnd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtEnd.requestFocus();

        } else {

            if (flag == 1) {
                mod.setCpf(Integer.parseInt(txtCpf.getText()));
                mod.setEndereco(txtEnd.getText());
                mod.setTelefone(Integer.parseInt(txtTel.getText()));
                mod.setNome(txtCpf.getText());
                mod.setCod_cidade(Integer.parseInt(kComboBoxCid.getSelectedItem().toString()));
                control.Salvar(mod);

                txtCod.setText("");
                txtCpf.setText("");
                txtEnd.setText("");
                txtNome.setText("");
                txtPesq.setText("");
                txtTel.setText("");
                btnBuscar.setEnabled(true);
                txtPesq.setEnabled(true);
                txtCpf.setEnabled(false);
                txtEnd.setEnabled(false);
                txtTel.setEnabled(false);
                
                kComboBoxCid.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                ktableCliente.setEnabled(true);
                //preencherTabela("select * from cidade order by nome");
            } else {
                mod.setCpf(Integer.parseInt(txtCpf.getText()));
                mod.setEndereco(txtEnd.getText());
                mod.setTelefone(Integer.parseInt(txtTel.getText()));
                mod.setNome(txtCpf.getText());
                mod.setCod_cidade(Integer.parseInt(kComboBoxCid.getSelectedItem().toString()));
                mod.setCodigo(Integer.parseInt(txtCod.getText()));
                control.Editar(mod);
                txtCpf.setEnabled(false);
                txtEnd.setEnabled(false);
                ktableCliente.setEnabled(false);
                txtNome.setEnabled(true);
                txtTel.setEnabled(true);
                txtCod.setText("");
                txtCpf.setText("");
                txtEnd.setText("");
                txtNome.setText("");
                txtPesq.setText("");
                txtTel.setText("");
                btnBuscar.setEnabled(true);
                txtPesq.setEnabled(true);
                txtCpf.setEnabled(false);
                txtEnd.setEnabled(false);
                txtTel.setEnabled(false);
                
                kComboBoxCid.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                ktableCliente.setEnabled(true);
                //preencherTabela("select * from cidade order by nome");
            }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtCpf.setEnabled(!true);
        txtCpf.setEnabled(!true);
        txtEnd.setEnabled(!true);
        txtNome.setEnabled(!true);
        txtTel.setEnabled(!true);
        btnSalvar.setEnabled(!true);
        btnCancelar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        txtPesq.setEnabled(true);
        btnBuscar.setEnabled(true);
        txtCod.setText("");
        txtCpf.setText("");
        txtEnd.setText("");
        txtNome.setText("");
        txtPesq.setText("");
        txtTel.setText("");
        ktableCliente.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:

        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja Apagar?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(txtCod.getText()));
            control.Apagar(mod);
            btnEditar.setEnabled(false);
            btnApagar.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtCpf.setEnabled(false);
            txtNome.setEnabled(false);
            kComboBoxCid.setEnabled(false);
            txtEnd.setEnabled(false);

            txtCod.setText("");
            txtCpf.setText("");
            txtEnd.setText("");
            txtNome.setText("");
            txtPesq.setText("");
            txtTel.setText("");
            //preencherTabela("select * from cliente order by nome");
            btnNovo.setEnabled(true);
            btnBuscar.setEnabled(true);
            txtPesq.setEnabled(true);

        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;
        kComboBoxCid.setEnabled(true);
        txtCpf.setEnabled(true);
        txtEnd.setEnabled(true);
        txtNome.setEnabled(true);
        txtPesq.setEnabled(true);
        txtTel.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnApagar.setEnabled(false);
        ktableCliente.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.cyber.componente.KComboBox kComboBoxCid;
    private br.com.cyber.componente.Ktable ktableCliente;
    private br.com.cyber.componente.KTextField txtCod;
    private br.com.cyber.componente.KTextField txtCpf;
    private br.com.cyber.componente.KTextField txtEnd;
    private br.com.cyber.componente.KTextField txtNome;
    private br.com.cyber.componente.KTextField txtPesq;
    private br.com.cyber.componente.KTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
