/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.CompraBean;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCompra;

/**
 *
 * @author luizk
 */
public class CadCompra extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoCompra control = new DaoCompra();
    CompraBean mod = new CompraBean();

    int flag = 0;

    /**
     * Creates new form CadCompra
     */
    public CadCompra() {
        initComponents();
        preencherTabelaCliente("select * from cliente order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        preencherTabelaFormapag("select * from forma_pagamento order by descricao");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrecoTotal = new br.com.cyber.componente.KTextField();
        txtCliente = new br.com.cyber.componente.KTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableCompra = new br.com.cyber.componente.Ktable();
        txtCodCliente = new br.com.cyber.componente.KTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCod = new br.com.cyber.componente.KTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ktableCliente = new br.com.cyber.componente.Ktable();
        txtData = new br.com.cyber.componente.KTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ktableForma = new br.com.cyber.componente.Ktable();
        btnBuscarForma = new javax.swing.JButton();
        txtForma = new br.com.cyber.componente.KTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCodFormapag = new br.com.cyber.componente.KTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cod-Pagamento:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 140, 150, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Data:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 80, 70, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Preço total:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 20, 100, 40);

        txtPrecoTotal.setEnabled(false);
        txtPrecoTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecoTotal.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtPrecoTotal.setK_placeholder_text("Total da compra");
        txtPrecoTotal.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtPrecoTotal);
        txtPrecoTotal.setBounds(150, 20, 240, 40);

        txtCliente.setEnabled(false);
        txtCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCliente.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtCliente.setK_placeholder_text("ex: \"Luiz\"");
        txtCliente.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtCliente);
        txtCliente.setBounds(100, 210, 110, 40);

        btnBuscarCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscarCliente.setEnabled(false);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarCliente);
        btnBuscarCliente.setBounds(210, 210, 80, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Pagamento:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(320, 210, 110, 40);

        btnNovo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo);
        btnNovo.setBounds(30, 410, 150, 50);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_save_1608823 (1).png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(190, 410, 150, 50);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_cancel-2_309095.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(350, 410, 160, 50);

        btnEditar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_edit_2561427.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);
        btnEditar.setBounds(520, 410, 150, 50);

        btnApagar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Streamline-70_185090.png"))); // NOI18N
        btnApagar.setText("APAGAR");
        btnApagar.setEnabled(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnApagar);
        btnApagar.setBounds(680, 410, 150, 50);

        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVoltar.setText("VOLTAR");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar);
        jButtonVoltar.setBounds(900, 440, 152, 40);

        ktableCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ktableCompra);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(630, 20, 452, 360);

        txtCodCliente.setEnabled(false);
        txtCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodClienteActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodCliente);
        txtCodCliente.setBounds(550, 80, 50, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CodCliente:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(430, 80, 100, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Código:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(460, 20, 70, 40);

        txtCod.setEnabled(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        jPanel2.add(txtCod);
        txtCod.setBounds(550, 20, 50, 40);

        ktableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableCliente.setEnabled(false);
        ktableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ktableCliente);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(30, 260, 260, 120);

        txtData.setEnabled(false);
        txtData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtData.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtData.setK_placeholder_text("AAAA-MM-DD");
        txtData.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtData);
        txtData.setBounds(150, 80, 240, 40);

        ktableForma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableForma.setEnabled(false);
        ktableForma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableFormaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ktableForma);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(320, 260, 300, 120);

        btnBuscarForma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscarForma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscarForma.setEnabled(false);
        btnBuscarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFormaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarForma);
        btnBuscarForma.setBounds(540, 210, 80, 40);

        txtForma.setEnabled(false);
        txtForma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtForma.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtForma.setK_placeholder_text("ex : \"Cheque\"");
        txtForma.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtForma);
        txtForma.setBounds(430, 210, 110, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cliente:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 210, 70, 40);

        txtCodFormapag.setEnabled(false);
        txtCodFormapag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodFormapagActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodFormapag);
        txtCodFormapag.setBounds(180, 140, 50, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 60, 1090, 490);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR COMPRA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 10, 1000, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 1160, 580);

        setSize(new java.awt.Dimension(1125, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        
        mod.setPesquisa(txtCliente.getText());
        
        preencherTabelaCliente("SELECT * FROM cliente WHERE nome LIKE '%" + mod.getPesquisa() + "%'");
         
        
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        btnNovo.setEnabled(false);
        txtPrecoTotal.setEnabled(true);
        txtData.setEnabled(true);
        btnBuscarForma.setEnabled(true);
        txtCliente.setEnabled(true);
        btnBuscarCliente.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtCliente.setText("");
        txtCodCliente.setText("");
        txtCod.setText("");
        txtCliente.setText("");
        txtCod.setText("");
        txtCodCliente.setText("");
        txtData.setText("");
        txtPrecoTotal.setText("");
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);
        
        ktableCliente.setEnabled(true);
        ktableCompra.setEnabled(false);
        ktableForma.setEnabled(true);
        txtForma.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtPrecoTotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtPrecoTotal.requestFocus();
        } else if (txtCodFormapag.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtCodFormapag.requestFocus();

        } else if (txtData.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtData.requestFocus();
        } else {

            if (flag == 1) {
                mod.setTotal(Integer.parseInt(txtPrecoTotal.getText()));
                mod.setData_(txtData.getText());
                mod.setCod_formapag(Integer.parseInt(txtCodFormapag.getText()));

                mod.setCod_cl(Integer.parseInt(txtCodCliente.getText()));
                control.Salvar(mod);

                txtCliente.setText("");
                txtCodCliente.setText("");
                txtCod.setText("");
                txtCliente.setText("");
                txtCod.setText("");
                txtCodCliente.setText("");
                txtData.setText("");
                txtPrecoTotal.setText("");

                btnBuscarCliente.setEnabled(false);
                

                txtPrecoTotal.setEnabled(false);
                txtData.setEnabled(false);
                txtCodFormapag.setEnabled(false);
                btnBuscarForma.setEnabled(false);
                txtCliente.setEnabled(false);

                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnNovo.setEnabled(true);
                ktableCliente.setEnabled(false);
                ktableCompra.setEnabled(true);
                preencherTabelaCliente("select * from cliente order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        preencherTabelaFormapag("select * from forma_pagamento order by descricao");

            } else if (flag != 1) {
                mod.setTotal(Integer.parseInt(txtPrecoTotal.getText()));
                mod.setData_(txtData.getText());
                mod.setCod_formapag(Integer.parseInt(txtCodFormapag.getText()));
                mod.setCodigo(Integer.parseInt(txtCod.getText()));
                mod.setCod_cl(Integer.parseInt(txtCodCliente.getText()));
                control.Editar(mod);

                txtCliente.setText("");
                txtCodCliente.setText("");
                txtCod.setText("");
                txtCliente.setText("");
                txtCod.setText("");
                txtCodCliente.setText("");
                txtData.setText("");
                txtPrecoTotal.setText("");

                
                txtCliente.setEnabled(false);
                txtCod.setEnabled(false);
                btnBuscarCliente.setEnabled(false);
               

                txtPrecoTotal.setEnabled(false);
                txtData.setEnabled(false);
                txtCodFormapag.setEnabled(false);
                btnBuscarForma.setEnabled(false);
                txtCliente.setEnabled(false);

                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnNovo.setEnabled(true);
                ktableCliente.setEnabled(false);
                ktableCompra.setEnabled(true);
                preencherTabelaCliente("select * from cliente order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        preencherTabelaFormapag("select * from forma_pagamento order by descricao");

            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        txtCliente.setEnabled(!true);
        txtCod.setEnabled(!true);
        txtData.setEnabled(!true);
        txtCliente.setEnabled(!true);
        txtPrecoTotal.setEnabled(!true);
        txtCodFormapag.setEnabled(false);
        btnBuscarForma.setEnabled(false);
        
        txtCliente.setText("");
        txtCodCliente.setText("");
        txtCod.setText("");
        txtCliente.setText("");
        txtCod.setText("");
        txtCodCliente.setText("");
        txtData.setText("");
        txtPrecoTotal.setText("");

        btnSalvar.setEnabled(!true);
        btnCancelar.setEnabled(!true);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnApagar.setEnabled(false);      
        ktableCliente.setEnabled(false);
        ktableCliente.setEnabled(true);
        preencherTabelaCliente("select * from cliente order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        preencherTabelaFormapag("select * from forma_pagamento order by descricao");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed

        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja Apagar?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(txtCod.getText()));
            control.Apagar(mod);
            btnEditar.setEnabled(false);
            btnApagar.setEnabled(false);
            btnCancelar.setEnabled(false);
            txtPrecoTotal.setEnabled(false);
            txtData.setEnabled(false);
            txtCliente.setEnabled(false);
            btnBuscarCliente.setEnabled(false);
            txtCodFormapag.setEnabled(false);
            btnBuscarForma.setEnabled(false);
            txtCod.setEnabled(false);
            txtCodCliente.setEnabled(false);
            txtCliente.setText("");
            txtCodCliente.setText("");
            txtCod.setText("");
            txtCliente.setText("");
            txtCod.setText("");
            txtCodCliente.setText("");
            txtData.setText("");
            txtPrecoTotal.setText("");
            txtCodFormapag.setText("");
            btnNovo.setEnabled(true);
            
            preencherTabelaCliente("select * from cliente order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        preencherTabelaFormapag("select * from forma_pagamento order by descricao");
        }

    }//GEN-LAST:event_btnApagarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void txtCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodClienteActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void ktableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableCompraMouseClicked

        int indice = ktableCompra.getSelectedRow();
        txtPrecoTotal.setText(ktableCompra.getValueAt(indice, 0).toString());
        txtData.setText(ktableCompra.getValueAt(indice, 1).toString());
        txtCod.setText(ktableCompra.getValueAt(indice, 2).toString());
        txtCodCliente.setText(ktableCompra.getValueAt(indice, 3).toString());
        txtCodFormapag.setText(ktableCompra.getValueAt(indice, 4).toString());
        btnEditar.setEnabled(true);
        btnApagar.setEnabled(true);
        btnNovo.setEnabled(false);

    }//GEN-LAST:event_ktableCompraMouseClicked

    private void ktableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableClienteMouseClicked
        int indice = ktableCliente.getSelectedRow();

        txtCodCliente.setText(ktableCliente.getValueAt(indice, 1).toString());
    }//GEN-LAST:event_ktableClienteMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag = 2;
        txtCliente.setEnabled(true);
        txtPrecoTotal.setEnabled(true);
        txtData.setEnabled(true);
        txtCodFormapag.setEnabled(true);
        btnBuscarForma.setEnabled(true);
        ktableCliente.setEnabled(true);
        txtCliente.setEnabled(true);
        btnBuscarCliente.setEnabled(true);
        ktableForma.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnApagar.setEnabled(false);

        ktableCliente.setEnabled(true);
        ktableCompra.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void ktableFormaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableFormaMouseClicked
        // TODO add your handling code here:
        int indice = ktableForma.getSelectedRow();

        txtCodFormapag.setText(ktableForma.getValueAt(indice, 1).toString());
    }//GEN-LAST:event_ktableFormaMouseClicked

    private void btnBuscarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFormaActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(txtForma.getText());
        
        preencherTabelaFormapag("SELECT * FROM forma_pagamento WHERE descricao LIKE '%" + mod.getPesquisa() + "%'");
    }//GEN-LAST:event_btnBuscarFormaActionPerformed

    private void txtCodFormapagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodFormapagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodFormapagActionPerformed
    public void preencherTabelaCliente(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"nome", "codigo"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getString("nome"),
                    conex.rs.getInt("codigo"),});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro cliente na tabela" + ex);

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        ktableCliente.setModel(modelo);
        ktableCliente.getColumnModel().getColumn(0).setPreferredWidth(180);
        ktableCliente.getColumnModel().getColumn(0).setResizable(false);
        ktableCliente.getColumnModel().getColumn(1).setPreferredWidth(120);
        ktableCliente.getColumnModel().getColumn(1).setResizable(false);

        ktableCliente.getTableHeader().setReorderingAllowed(false);

        ktableCliente.setAutoResizeMode(ktableCliente.AUTO_RESIZE_OFF);
        ktableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    public void preencherTabelaFormapag(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"descricao", "codigo"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getString("descricao"),
                    conex.rs.getInt("codigo"),});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro cliente na tabela" + ex);

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        ktableForma.setModel(modelo);
        ktableForma.getColumnModel().getColumn(0).setPreferredWidth(180);
        ktableForma.getColumnModel().getColumn(0).setResizable(false);
        ktableForma.getColumnModel().getColumn(1).setPreferredWidth(120);
        ktableForma.getColumnModel().getColumn(1).setResizable(false);

        ktableForma.getTableHeader().setReorderingAllowed(false);

        ktableForma.setAutoResizeMode(ktableForma.AUTO_RESIZE_OFF);
        ktableForma.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    public void preencherTabelaCompra(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"total", "data_", "codigo", "cod_cl", "cod_formapag"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getInt("total"),
                    conex.rs.getString("data_"),
                    conex.rs.getInt("codigo"),
                    conex.rs.getInt("cod_cl"),
                    conex.rs.getInt("cod_formapag")
                });
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro codigo de compra na tabela" + ex);

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        ktableCompra.setModel(modelo);
        ktableCompra.getColumnModel().getColumn(0).setPreferredWidth(100);
        ktableCompra.getColumnModel().getColumn(0).setResizable(false);
        ktableCompra.getColumnModel().getColumn(1).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(1).setResizable(false);
        ktableCompra.getColumnModel().getColumn(2).setPreferredWidth(80);
        ktableCompra.getColumnModel().getColumn(2).setResizable(false);
        ktableCompra.getColumnModel().getColumn(3).setPreferredWidth(80);
        ktableCompra.getColumnModel().getColumn(3).setResizable(false);
        ktableCompra.getColumnModel().getColumn(4).setPreferredWidth(80);
        ktableCompra.getColumnModel().getColumn(4).setResizable(false);

        ktableCompra.getTableHeader().setReorderingAllowed(false);

        ktableCompra.setAutoResizeMode(ktableCompra.AUTO_RESIZE_OFF);
        ktableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarForma;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private br.com.cyber.componente.Ktable ktableCliente;
    private br.com.cyber.componente.Ktable ktableCompra;
    private br.com.cyber.componente.Ktable ktableForma;
    private br.com.cyber.componente.KTextField txtCliente;
    private br.com.cyber.componente.KTextField txtCod;
    private br.com.cyber.componente.KTextField txtCodCliente;
    private br.com.cyber.componente.KTextField txtCodFormapag;
    private br.com.cyber.componente.KTextField txtData;
    private br.com.cyber.componente.KTextField txtForma;
    private br.com.cyber.componente.KTextField txtPrecoTotal;
    // End of variables declaration//GEN-END:variables
}
