/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author luizk
 */
public class CadLojaProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadLojaProduto
     */
    public CadLojaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableProduto = new br.com.cyber.componente.Ktable();
        txtProduto = new br.com.cyber.componente.KTextField();
        btnBuscarProd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ktableCompra = new br.com.cyber.componente.Ktable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        ktableProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableProduto.setEnabled(false);
        ktableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ktableProduto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 250, 280, 170);

        txtProduto.setEnabled(false);
        txtProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProduto.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtProduto.setK_placeholder_text("Digite o nome do produto");
        txtProduto.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        jPanel2.add(txtProduto);
        txtProduto.setBounds(30, 200, 180, 40);

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscarProd.setEnabled(false);
        jPanel2.add(btnBuscarProd);
        btnBuscarProd.setBounds(210, 200, 100, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("SELECIONA A COMPRA");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(330, 200, 160, 40);

        ktableCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableCompra.setEnabled(false);
        ktableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ktableCompra);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(330, 250, 270, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButton2.setEnabled(false);
        jPanel2.add(jButton2);
        jButton2.setBounds(490, 200, 110, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 50, 1010, 520);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1080, 600);

        setSize(new java.awt.Dimension(1055, 588));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ktableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableProdutoMouseClicked
        // TODO add your handling code here:
        int indice = ktableProduto.getSelectedRow();

        txtCodProd.setText(ktableProduto.getValueAt(indice, 1).toString());
    }//GEN-LAST:event_ktableProdutoMouseClicked

    private void ktableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableCompraMouseClicked
        // TODO add your handling code here:
        int indice = ktableCompra.getSelectedRow();

        txtCodCompra.setText(ktableCompra.getValueAt(indice, 2).toString());
    }//GEN-LAST:event_ktableCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadLojaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadLojaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadLojaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadLojaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadLojaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private br.com.cyber.componente.Ktable ktableCompra;
    private br.com.cyber.componente.Ktable ktableProduto;
    private br.com.cyber.componente.KTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
