/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import modeloBeans.ProdCompraBean;
import modeloConnection.ConexaoBD;
import modeloDao.DaoProdCompra;

/**
 *
 * @author luizk
 */
public class CadProdCompra extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    DaoProdCompra control = new DaoProdCompra();
    ProdCompraBean mod = new ProdCompraBean();
    
    int flag = 0;

    /**
     * Creates new form CadProdCOmpra
     */
    public CadProdCompra() {
        initComponents();
        preencherTabelaProduto("select * from produto order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableProduto = new br.com.cyber.componente.Ktable();
        txtProduto = new br.com.cyber.componente.KTextField();
        btnBuscarProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new br.com.cyber.componente.KTextField();
        txtValor = new br.com.cyber.componente.KTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ktableCompra = new br.com.cyber.componente.Ktable();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtVf = new br.com.cyber.componente.KTextField();
        btnFInalizar = new javax.swing.JButton();
        txtCodCompra = new br.com.cyber.componente.KTextField();
        txtCodProd = new br.com.cyber.componente.KTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButtonVoltar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        ktableProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableProduto.setEnabled(false);
        ktableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ktableProduto);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 280, 280, 170);

        txtProduto.setEnabled(false);
        txtProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProduto.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtProduto.setK_placeholder_text("Digite o nome do produto");
        txtProduto.setK_placeholder_text_color(new java.awt.Color(51, 51, 51));
        jPanel2.add(txtProduto);
        txtProduto.setBounds(30, 230, 180, 40);

        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        btnBuscarProd.setEnabled(false);
        jPanel2.add(btnBuscarProd);
        btnBuscarProd.setBounds(210, 230, 100, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VALOR FINAL(R$):");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 160, 130, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("COD COMP");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(410, 90, 90, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("QUANTIDADE:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 90, 120, 40);

        txtQuantidade.setEnabled(false);
        txtQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQuantidade.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtQuantidade.setK_placeholder_text("Insira a quantiade APENAS INTEIROS");
        txtQuantidade.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        jPanel2.add(txtQuantidade);
        txtQuantidade.setBounds(110, 90, 290, 40);

        txtValor.setEnabled(false);
        txtValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtValor.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtValor.setK_placeholder_text("Insira o valor da compra APENAS INTEIROS");
        txtValor.setK_placeholder_text_color(new java.awt.Color(102, 102, 102));
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        jPanel2.add(txtValor);
        txtValor.setBounds(110, 30, 290, 40);

        ktableCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableCompra.setEnabled(false);
        ktableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ktableCompra);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(330, 280, 270, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButton2.setEnabled(false);
        jPanel2.add(jButton2);
        jButton2.setBounds(490, 230, 110, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("SELECIONA A COMPRA");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(330, 230, 160, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VALOR(R$):");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 30, 120, 40);

        txtVf.setEnabled(false);
        txtVf.setK_back_focus_gained(new java.awt.Color(255, 255, 255));
        txtVf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVfActionPerformed(evt);
            }
        });
        jPanel2.add(txtVf);
        txtVf.setBounds(170, 160, 100, 40);

        btnFInalizar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnFInalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_35-Gear_2674077.png"))); // NOI18N
        btnFInalizar.setText("FINALIZAR");
        btnFInalizar.setEnabled(false);
        btnFInalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFInalizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnFInalizar);
        btnFInalizar.setBounds(610, 80, 340, 60);

        txtCodCompra.setEnabled(false);
        jPanel2.add(txtCodCompra);
        txtCodCompra.setBounds(500, 90, 90, 40);

        txtCodProd.setEnabled(false);
        jPanel2.add(txtCodProd);
        txtCodProd.setBounds(500, 30, 90, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("PRODUTO:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 220, 90, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("COD PROD");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 30, 90, 40);

        btnNovo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.png"))); // NOI18N
        btnNovo.setText("NOVO");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo);
        btnNovo.setBounds(610, 10, 340, 60);

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_save_1608823 (1).png"))); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(610, 220, 340, 60);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_cancel-2_309095.png"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(610, 150, 340, 60);

        jButtonVoltar2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonVoltar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButtonVoltar2.setText("VOLTAR");
        jButtonVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar2);
        jButtonVoltar2.setBounds(690, 340, 170, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 70, 960, 470);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Compra Produto");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 920, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 1050, 580);

        setSize(new java.awt.Dimension(1008, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtVfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVfActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void btnFInalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFInalizarActionPerformed
        // TODO add your handling code here:
        
        if ((txtQuantidade.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "preencha todos os campos para continuar!");
            txtQuantidade.requestFocus();
            
        } else if (txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha todos os campos para continuar!");
            txtValor.requestFocus();
            
        } else if (txtCodCompra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione a compra para continuar!");
            ktableCompra.requestFocus();
            
        } else if (txtCodProd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione o produto para continuar!!");
            ktableProduto.requestFocus();            
            
        } else {
            flag = 2;
            int result;
            result = Integer.parseInt(txtValor.getText()) * Integer.parseInt(txtQuantidade.getText());
            txtVf.setText(String.valueOf(result));
            btnSalvar.setEnabled(true);
            ktableCompra.setEnabled(false);
            ktableProduto.setEnabled(false);
            txtProduto.setEnabled(false);
            txtQuantidade.setEnabled(false);
            txtValor.setEnabled(false);
            txtVf.setEnabled(false);
            btnFInalizar.setEnabled(false);
            btnCancelar.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnFInalizarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        btnNovo.setEnabled(false);
        txtValor.setEnabled(true);
        txtQuantidade.setEnabled(true);
        txtProduto.setEnabled(true);
        btnBuscarProd.setEnabled(true);
        btnFInalizar.setEnabled(true);
        txtCodCompra.setText("");
        txtCodProd.setText("");
        txtProduto.setText("");
        txtQuantidade.setText("");
        txtVf.setText("");
        txtValor.setText("");
        
        ktableCompra.setEnabled(true);
        ktableProduto.setEnabled(true);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if (txtQuantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtQuantidade.requestFocus();
        } else if (txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para continuar!");
            txtValor.requestFocus();
        } else {
            
            if (flag == 1) {
                JOptionPane.showMessageDialog(null, "Compra não finalizada!");
                btnFInalizar.requestFocus();
                
            } else if (flag != 1) {
                mod.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
                mod.setValor(Integer.parseInt(txtValor.getText()));
                mod.setCod_prod(Integer.parseInt(txtCodProd.getText()));
                mod.setCod_compra(Integer.parseInt(txtCodCompra.getText()));
                control.Salvar(mod);
                
                txtCodCompra.setText("");
                txtCodProd.setText("");
                txtProduto.setText("");
                txtQuantidade.setText("");
                txtVf.setText("");
                txtValor.setText("");
                
                btnBuscarProd.setEnabled(false);
                
                btnNovo.setEnabled(!false);
                txtValor.setEnabled(!true);
                txtQuantidade.setEnabled(!true);
                txtProduto.setEnabled(!true);
                btnBuscarProd.setEnabled(!true);
                btnFInalizar.setEnabled(!true);
                
                btnSalvar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnNovo.setEnabled(true);
                ktableProduto.setEnabled(false);
                ktableCompra.setEnabled(false);
                preencherTabelaProduto("select * from produto order by nome");
                preencherTabelaCompra("select * from compra order by codigo");
                
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnNovo.setEnabled(true);
        txtCodCompra.setEnabled(!true);
        txtCodProd.setEnabled(!true);
        txtProduto.setEnabled(!true);
        txtQuantidade.setEnabled(!true);
        txtValor.setEnabled(!true);
        txtVf.setEnabled(false);
        btnBuscarProd.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnFInalizar.setEnabled(false);
        btnCancelar.setEnabled(true);
        txtCodCompra.setText("");
        txtCodProd.setText("");
        txtProduto.setText("");
        txtQuantidade.setText("");
        txtVf.setText("");
        txtValor.setText("");
        
        ktableCompra.setEnabled(false);
        ktableProduto.setEnabled(false);
        preencherTabelaProduto("select * from produto order by nome");
        preencherTabelaCompra("select * from compra order by codigo");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        byte resposta = 0;
        resposta  = (byte) JOptionPane.showConfirmDialog(rootPane, "Deseja voltar? Seus dados não salvos serão perdidos!");
        if(resposta ==  JOptionPane.YES_OPTION){
        dispose();
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void ktableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableProdutoMouseClicked
        // TODO add your handling code here:
        int indice = ktableProduto.getSelectedRow();
        
        txtCodProd.setText(ktableProduto.getValueAt(indice, 1).toString());
    }//GEN-LAST:event_ktableProdutoMouseClicked

    private void ktableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableCompraMouseClicked
        // TODO add your handling code here:
        int indice = ktableCompra.getSelectedRow();
        
        txtCodCompra.setText(ktableCompra.getValueAt(indice, 2).toString());
    }//GEN-LAST:event_ktableCompraMouseClicked
    public void preencherTabelaCompra(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"total", "data_", "codigo"};
        conex.conexao();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getInt("total"),
                    conex.rs.getString("data_"),
                    conex.rs.getInt("codigo"),});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro codigo de compra na tabela" + ex);
            
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        ktableCompra.setModel(modelo);
        ktableCompra.getColumnModel().getColumn(0).setPreferredWidth(90);
        ktableCompra.getColumnModel().getColumn(0).setResizable(false);
        ktableCompra.getColumnModel().getColumn(1).setPreferredWidth(90);
        ktableCompra.getColumnModel().getColumn(1).setResizable(false);
        ktableCompra.getColumnModel().getColumn(2).setPreferredWidth(90);
        
        ktableCompra.getTableHeader().setReorderingAllowed(false);
        
        ktableCompra.setAutoResizeMode(ktableCompra.AUTO_RESIZE_OFF);
        ktableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    public void preencherTabelaProduto(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"nome", "codigo"};
        conex.conexao();
        conex.executaSql(Sql);
        
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("nome"), conex.rs.getInt("codigo")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro produto na tabela");
            
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        
        ktableProduto.setModel(modelo);
        ktableProduto.getColumnModel().getColumn(0).setPreferredWidth(400);
        ktableProduto.getColumnModel().getColumn(0).setResizable(false);
        ktableProduto.getColumnModel().getColumn(1).setPreferredWidth(110);
        ktableProduto.getColumnModel().getColumn(1).setResizable(false);
        
        ktableProduto.setAutoResizeMode(ktableProduto.AUTO_RESIZE_OFF);
        ktableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProdCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFInalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonVoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private br.com.cyber.componente.Ktable ktableCompra;
    private br.com.cyber.componente.Ktable ktableProduto;
    private br.com.cyber.componente.KTextField txtCodCompra;
    private br.com.cyber.componente.KTextField txtCodProd;
    private br.com.cyber.componente.KTextField txtProduto;
    private br.com.cyber.componente.KTextField txtQuantidade;
    private br.com.cyber.componente.KTextField txtValor;
    private br.com.cyber.componente.KTextField txtVf;
    // End of variables declaration//GEN-END:variables
}
