/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ClienteBean;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author luizk
 */
public class TelaBuscaCliente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoCliente control = new DaoCliente();
    ClienteBean mod =  new ClienteBean();
    /**
     * Creates new form TelaBuscaLoja
     */
    public TelaBuscaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCliente = new br.com.cyber.componente.Ktable();
        jButton1 = new javax.swing.JButton();
        jTextFieldPesquisa = new br.com.cyber.componente.KTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jtableCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableCliente);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(310, 10, 600, 390);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 360, 170, 40);
        jPanel2.add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(20, 30, 260, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Código:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 290, 80, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Endereço:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 200, 80, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Telefone:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 230, 80, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar.png"))); // NOI18N
        jButton2.setText("PESQUISAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 80, 170, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Nome:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 260, 80, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CPF:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 80, 20);
        jPanel2.add(lblCod);
        lblCod.setBounds(110, 290, 120, 20);
        jPanel2.add(lblNome);
        lblNome.setBounds(110, 260, 120, 20);
        jPanel2.add(lblEnd);
        lblEnd.setBounds(110, 200, 120, 20);
        jPanel2.add(lblTel);
        lblTel.setBounds(110, 230, 120, 20);
        jPanel2.add(lblCpf);
        lblCpf.setBounds(110, 170, 120, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Cidade:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 320, 80, 20);
        jPanel2.add(lblCid);
        lblCid.setBounds(110, 320, 120, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 50, 920, 410);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PESQUISA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 920, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-90, 0, 1100, 500);

        setSize(new java.awt.Dimension(982, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        mod.setClientePesquisa(jTextFieldPesquisa.getText());
        ClienteBean model = control.buscaCliente(mod);
        lblCpf.setText(String.valueOf(model.getCpf()));
        lblEnd.setText(model.getEndereco());
        lblTel.setText(String.valueOf(model.getTelefone()));
        lblNome.setText(model.getNome());
        lblCod.setText(String.valueOf(model.getCodigo()));
        lblCid.setText(String.valueOf(model.getCod_cidade()));
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"nome", "cep", "uf", "codigo"};
        conex.conexao();
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getString("nome"), conex.rs.getInt("Telefone"), conex.rs.getString("Telefone"), conex.rs.getInt("codigo")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outra cidade na tabela");

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jtableCliente.setModel(modelo);
        jtableCliente.getColumnModel().getColumn(0).setPreferredWidth(215);
        jtableCliente.getColumnModel().getColumn(0).setResizable(false);
        jtableCliente.getColumnModel().getColumn(1).setPreferredWidth(150);
        jtableCliente.getColumnModel().getColumn(1).setResizable(false);
        jtableCliente.getColumnModel().getColumn(2).setPreferredWidth(80);
        jtableCliente.getColumnModel().getColumn(2).setResizable(false);
        jtableCliente.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtableCliente.getColumnModel().getColumn(3).setResizable(false);
        jtableCliente.getTableHeader().setReorderingAllowed(false);

        jtableCliente.setAutoResizeMode(jtableCliente.AUTO_RESIZE_OFF);
        jtableCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.cyber.componente.KTextField jTextFieldPesquisa;
    private br.com.cyber.componente.Ktable jtableCliente;
    private javax.swing.JLabel lblCid;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTel;
    // End of variables declaration//GEN-END:variables
}
