/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ClienteBean;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoCliente;

/**
 *
 * @author luizk
 */
public class TelaBuscaCompra extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoCliente control = new DaoCliente();
    ClienteBean mod = new ClienteBean();

    /**
     * Creates new form TelaBuscaLoja
     */
    public TelaBuscaCompra() {
        initComponents();
        preencherTabelaCompra("select * from compra order by codigo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableCompra = new br.com.cyber.componente.Ktable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCodpag = new javax.swing.JLabel();
        lvlTotal = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblCodCli = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        ktableCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ktableCompra);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(340, 10, 590, 390);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 360, 170, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código Pagamento:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(33, 300, 173, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Data:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 190, 160, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código Compra:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 220, 150, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Total: (R$)");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 150, 150, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Código Cliente:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 260, 160, 20);

        lblCodpag.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(lblCodpag);
        lblCodpag.setBounds(220, 300, 100, 20);

        lvlTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(lvlTotal);
        lvlTotal.setBounds(210, 150, 110, 20);

        lblData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(lblData);
        lblData.setBounds(210, 190, 110, 20);

        lblCod.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(lblCod);
        lblCod.setBounds(210, 220, 110, 20);

        lblCodCli.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(lblCodCli);
        lblCodCli.setBounds(210, 260, 110, 20);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("DESCRESCENTE");
        jButton2.setToolTipText("maior para menor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(110, 70, 200, 50);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("CRESCENTE ");
        jButton3.setToolTipText("menor para maior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(110, 10, 200, 50);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("     Código:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 60, 90, 22);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);
        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 130, 310, 200);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Organizar");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 40, 90, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 50, 940, 410);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PESQUISA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 920, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-90, 0, 1100, 500);

        setSize(new java.awt.Dimension(982, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ktableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableCompraMouseClicked
        // TODO add your handling code here:
        int indice = ktableCompra.getSelectedRow();
        lvlTotal.setText(ktableCompra.getValueAt(indice, 0).toString());
        lblData.setText(ktableCompra.getValueAt(indice, 1).toString());
        lblCod.setText(ktableCompra.getValueAt(indice, 2).toString());
        lblCodCli.setText(ktableCompra.getValueAt(indice, 3).toString());
        lblCodpag.setText(ktableCompra.getValueAt(indice, 4).toString());
        

    }//GEN-LAST:event_ktableCompraMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
preencherTabelaCompra("select * from compra order by codigo desc");
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        preencherTabelaCompra("select * from compra order by codigo asc");

    }//GEN-LAST:event_jButton3ActionPerformed
    public void preencherTabelaCompra(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"total", "data_", "codigo", "cod_cl", "cod_formapag"};
        conex.conexao();                  
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getInt("total"),
                    conex.rs.getString("data_"),
                    conex.rs.getInt("codigo"),
                    conex.rs.getInt("cod_cl"),
                    conex.rs.getInt("cod_formapag")
                });
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro codigo de compra na tabela" + ex);

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        ktableCompra.setModel(modelo);
        ktableCompra.getColumnModel().getColumn(0).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(0).setResizable(false);
        ktableCompra.getColumnModel().getColumn(1).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(1).setResizable(false);
        ktableCompra.getColumnModel().getColumn(2).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(2).setResizable(false);
        ktableCompra.getColumnModel().getColumn(3).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(3).setResizable(false);
        ktableCompra.getColumnModel().getColumn(4).setPreferredWidth(120);
        ktableCompra.getColumnModel().getColumn(4).setResizable(false);

        ktableCompra.getTableHeader().setReorderingAllowed(false);

        ktableCompra.setAutoResizeMode(ktableCompra.AUTO_RESIZE_OFF);
        ktableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.cyber.componente.Ktable ktableCompra;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCodCli;
    private javax.swing.JLabel lblCodpag;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lvlTotal;
    // End of variables declaration//GEN-END:variables
}
