/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.ModeloTabela;
import modeloBeans.ProdCompraBean;
import modeloConnection.ConexaoBD;
import modeloDao.DaoProdCompra;

/**
 *
 * @author luizk
 */
public class TelaBuscaProdutoCompra extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    DaoProdCompra control = new DaoProdCompra();
    ProdCompraBean mod = new ProdCompraBean();

    /**
     * Creates new form TelaBuscaLoja
     */
    public TelaBuscaProdutoCompra() {
        initComponents();
        preencherTabelaProdCompra("select * from prod_compra order by valor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ktableProdCompra = new br.com.cyber.componente.Ktable();
        jButton1 = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gbg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lvlQuantidade = new javax.swing.JLabel();
        lblCodProd = new javax.swing.JLabel();
        lblCodCompra = new javax.swing.JLabel();
        gbg1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lSOme = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        ktableProdCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ktableProdCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ktableProdCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktableProdCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ktableProdCompra);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(390, 10, 540, 390);

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_ic_keyboard_return_48px_352473.png"))); // NOI18N
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(20, 360, 170, 40);

        btnApagar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Streamline-70_185090.png"))); // NOI18N
        btnApagar.setText("APAGAR");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnApagar);
        btnApagar.setBounds(50, 280, 280, 60);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("CodCompra:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 230, 110, 30);

        gbg.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gbg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gbg.setText("ORGANIZAR TABELA:");
        jPanel2.add(gbg);
        gbg.setBounds(90, 10, 200, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 170, 110, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("CodProduto:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 200, 110, 30);

        lblValor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(lblValor);
        lblValor.setBounds(170, 140, 180, 30);

        lvlQuantidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(lvlQuantidade);
        lvlQuantidade.setBounds(170, 170, 180, 30);

        lblCodProd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(lblCodProd);
        lblCodProd.setBounds(170, 200, 180, 30);

        lblCodCompra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(lblCodCompra);
        lblCodCompra.setBounds(170, 230, 180, 30);

        gbg1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        gbg1.setText("Valor:");
        jPanel2.add(gbg1);
        gbg1.setBounds(50, 140, 110, 30);

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("DECRESCENTE");
        jButton2.setToolTipText("maior para menor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 50, 180, 70);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("CRESCENTE ");
        jButton3.setToolTipText("menor para maior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 50, 180, 70);

        lSOme.setText("SELECIONE UM ITEM NA TABELA ");
        jPanel2.add(lSOme);
        lSOme.setBounds(180, 120, 220, 150);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 50, 940, 410);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PESQUISA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 10, 920, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-90, 0, 1100, 500);

        setSize(new java.awt.Dimension(982, 487));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ktableProdCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktableProdCompraMouseClicked
        // TODO add your handling code here:
        lSOme.setText(null);
        int indice = ktableProdCompra.getSelectedRow();
        lblValor.setText(ktableProdCompra.getValueAt(indice, 0).toString());
        lvlQuantidade.setText(ktableProdCompra.getValueAt(indice, 1).toString());
        lblCodProd.setText(ktableProdCompra.getValueAt(indice, 2).toString());
        lblCodCompra.setText(ktableProdCompra.getValueAt(indice, 3).toString());
        
        

    }//GEN-LAST:event_ktableProdCompraMouseClicked

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Realmente deseja Apagar?");
        if (resposta == JOptionPane.YES_OPTION) {
            mod.setCod_prod(Integer.parseInt(lblCodProd.getText()));
            mod.setCod_compra(Integer.parseInt(lblCodCompra.getText()));
            control.Apagar(mod);
            
                    
        
            lblCodCompra.setText("");
            lblValor.setText("");
            lblCodProd.setText("");
            lvlQuantidade.setText("");
            
            preencherTabelaProdCompra("select * from prod_compra order by valor");
         

        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        preencherTabelaProdCompra("select * from prod_compra order by valor DESC");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        preencherTabelaProdCompra("select * from prod_compra order by valor DESC");
    }//GEN-LAST:event_jButton3ActionPerformed
    public void preencherTabelaProdCompra(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"quantidade", "valor", "cod_prod", "cod_compra"};
        conex.conexao();                  
        conex.executaSql(Sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{
                    conex.rs.getInt("quantidade"),
                    conex.rs.getString("valor"),
                    conex.rs.getInt("cod_prod"),
                    conex.rs.getInt("cod_compra"),                   
                });
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque outro codigo de compra na tabela" + ex);

        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        ktableProdCompra.setModel(modelo);
        ktableProdCompra.getColumnModel().getColumn(0).setPreferredWidth(170);
        ktableProdCompra.getColumnModel().getColumn(0).setResizable(false);
        ktableProdCompra.getColumnModel().getColumn(1).setPreferredWidth(180);
        ktableProdCompra.getColumnModel().getColumn(1).setResizable(false);
        ktableProdCompra.getColumnModel().getColumn(2).setPreferredWidth(95);
        ktableProdCompra.getColumnModel().getColumn(2).setResizable(false);
        ktableProdCompra.getColumnModel().getColumn(3).setPreferredWidth(95);
        ktableProdCompra.getColumnModel().getColumn(3).setResizable(false);
       

        ktableProdCompra.getTableHeader().setReorderingAllowed(false);

        ktableProdCompra.setAutoResizeMode(ktableProdCompra.AUTO_RESIZE_OFF);
        ktableProdCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProdutoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProdutoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProdutoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBuscaProdutoCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBuscaProdutoCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JLabel gbg;
    private javax.swing.JLabel gbg1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private br.com.cyber.componente.Ktable ktableProdCompra;
    private javax.swing.JLabel lSOme;
    private javax.swing.JLabel lblCodCompra;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lvlQuantidade;
    // End of variables declaration//GEN-END:variables
}
